ModalView:
    on_open: app.open_modal(self)
    on_dismiss: app.close_modal(self)

    background_color: (0, 0, 0, 0.3)
    opacity: 0

    RelativeLayout:

        MDCustomCard:
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            size_hint: None, None
            size: app.x() - dp(80), dp(180)
            radius: [dp(20),]
            md_bg_color: app.theme_cls.bg_light

            RelativeLayout:

                MDLabel:
                    id: la
                    text: "Do you want to exit?"
                    font_name: "assets/Poppins-Medium.ttf"
                    halign: "center"
                    valign: "middle"
                    pos_hint: {"center_x": 0.5, "center_y": 0.65}

                MDFlatButton:
                    id: cb
                    pos_hint: {"center_x": 0.3, "center_y": 0.2}
                    text: "Cancel"
                    font_name: "assets/Poppins-Regular.ttf"
                    theme_text_color: "Custom"
                    text_color: app.theme_cls.primary_color
                    on_press: root.dismiss()

                MDFlatButton:
                    id: fb
                    pos_hint: {"center_x": 0.7, "center_y": 0.2}
                    text: "Exit"
                    font_name: "assets/Poppins-Regular.ttf"
                    theme_text_color: "Custom"
                    text_color: app.theme_cls.primary_color
                    on_press: app.exit_app()
