<ListSwitch@MDBoxLayout>:
    text: ""
    active: False
    s_press: app.do_nothing

    size_hint: None, None
    size: app.x(), dp(50)
    padding: dp(10)

    RelativeLayout:

        MDLabel:
            text: root.text
            font_name: "assets/Poppins-Medium.ttf"
            font_size: "15sp"
            pos_hint: {"center_y": 0.5}

        MDSwitch:
            pos_hint: {"center_x": 0.85, "center_y": 0.5}
            active: root.active
            on_active: root.s_press(self, self.active)


<ListIcon@MDBoxLayout>:
    text: ""
    size_hint: None, None
    size: app.x(), dp(50)
    padding: dp(10)
    press: app.do_nothing

    RelativeLayout:

        MDLabel:
            text: root.text
            font_name: "assets/Poppins-Medium.ttf"
            font_size: "15sp"
            pos_hint: {"center_y": 0.5}

        MDIconButton:
            icon: "chevron-right"
            pos_hint: {"center_x": 0.9, "center_y": 0.5}
            on_press: root.press()


ModalView:
    on_open: app.open_modal(self)
    on_dismiss: app.close_modal(self)
    background_color: app.theme_cls.bg_normal
    opacity: 0

    MDRelativeLayout:
        md_bg_color: app.theme_cls.bg_normal

        MDLabel:
            pos_hint: {"center_x": 0.5, "center_y": 0.95}
            text: "Settings"
            bold: True
            font_name: "assets/Poppins-Bold.ttf"
            font_size: "35sp"

        MDCustomCard:
            size_hint: None, None
            size: app.x(), dp(320)
            pos_hint: {"center_x": 0.5, "center_y": 0.65}
            md_bg_color: 0, 0, 0, 0
            orientation: "vertical"
            padding: dp(10)

            ListSwitch:
                text: "Dark mode"
                active: app.read_settings()[0]
                s_press: app.set_mode

            ListSwitch:
                text: "Save chats"
                active: app.read_settings()[1] if len(app.read_settings()) > 1 else False

            MDSeparator:

            ListIcon:
                text: "Change primary color"
                press: lambda: app.open_theme_changer("primary")

            ListIcon:
                text: "Change accent color"
                press: lambda: app.open_theme_changer("accent")

            ListIcon:
                text: "Change chat wallpaper"
                press: app.open_wall

            ListIcon:
                text: "Change chat save path"
                press: app.open_save_path
