<ThemeCircle>:
    size_hint: None, None
    size: dp(50), dp(50)
    radius: [dp(50),]
    # md_bg_color: app.theme_cls.primary_color

    on_press:
        app.change_color_theme(self.text, self.cht)


ModalView:
    on_open: app.open_modal(self)
    on_dismiss: app.close_modal(self)
    background_color: 0, 0, 0, 0
    opacity: 0

    RelativeLayout:

        MDCustomCard:
            pos_hint: {"center_x": 0.5, "center_y": 0.55}
            size_hint: None, None
            size: app.x() - dp(40), (app.y() / 2) + dp(40)
            md_bg_color: app.theme_cls.bg_normal
            radius: dp(20)

            RelativeLayout:

                AnchorLayout:
                    anchor_y: "top"

                    MDCustomCard:
                        id: tc
                        size_hint: None, None
                        size: app.x() - dp(40), dp(50)
                        radius: [dp(20), dp(20), 0, 0]
                        md_bg_color: app.theme_cls.primary_color

                        MDLabel:
                            id: tl
                            text: "Primary Color"
                            font_name: "assets/Poppins-Medium.ttf"
                            halign: "center"
                            valign: "middle"

                MDGridLayout:
                    id: theme_box
                    pos_hint: {"center_x": 0.5, "center_y": 0.45}
                    size_hint_x: 0.9
                    size_hint_y: 0.8
                    cols: 4
                    rows: 4
                    spacing: dp(25)
                    padding: dp(15)
                    adaptive_height: True
